version: "2.1"
services:
  react:
    container_name: jira-cdd-$CI_BUILD_REF_NAME.hipay-pos-platform.com
    image: cdd-react-$CI_BUILD_REF_NAME
    ports:
      - "5123:5000"
    env_file:
      - ./conf/env_file/env.ci
    links:
      - php
  php:
    container_name: cdd-php-dev-$CI_BUILD_REF_NAME
    image: cdd-php-$CI_BUILD_REF_NAME
    ports:
      - "8041:80"
    env_file:
      - ./conf/env_file/env.ci
    labels:
      io.rancher.container.start_once: 'true'
  hostedfields:
    container_name: cdd-hostedfields-dev-$CI_BUILD_REF_NAME
    image: cdd-hostedfields-$CI_BUILD_REF_NAME
    ports:
      - "9123:80"
    env_file:
      - ./conf/env_file/env.ci