# You should always specify a full version here to ensure all of your developers
# are running the same version of Node.
FROM node:9.3.0

MAINTAINER PI - Ecommerce  <pi-ecommerce@hipay.com>

# Install and configure `serve`.
RUN npm install -g serve
CMD serve -s build
EXPOSE 5000

# Install all dependencies of the current project.
COPY react/package.json package.json
RUN npm install

# Copy all local files into the image.
COPY react .

# Build for production.
RUN npm run build --production

